# Generated by Django 5.1.7 on 2025-03-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_availablepool_team_userprofile_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='serving_pincodes',
            field=models.TextField(blank=True, help_text='Comma-separated pincodes'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pin_code',
            field=models.CharField(max_length=6),
        ),
    ]
