# Generated by Django 5.1.7 on 2025-03-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0006_task_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='allocatedHours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
