# Generated by Django 5.1.7 on 2025-03-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0007_task_allocatedhours_task_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='allocatedHours',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
